SWITCH_ON=yes
SAVE_VIDEO_ON_MOTION=yes
SENSITIVITY=low
SOUND_DETECTION=no
SOUND_SENSITIVITY=80
BABY_CRYING_DETECT=no
LED=yes
ROTATE=no
IR=yes
MOTION_DETECTION=yes
AI_HUMAN_DETECTION=yes
AI_VEHICLE_DETECTION=yes
AI_ANIMAL_DETECTION=yes
FACE_DETECTION=yes
MOTION_TRACKING=yes
CRUISE=yes
